export type { MetaSocialData } from "./types";

export { extractMetaSocial, firstValue } from "./extract";

export { hasCharsetInFirstKB, CHARSET_WINDOW_BYTES } from "./charset";

export {
  OG_TITLE_MIN,
  OG_TITLE_MAX,
  OG_DESC_MIN,
  OG_DESC_MAX,
  MAX_MEASURED_VALUE_CHARS,
  TWITTER_CARD_VALUES,
  OG_IMAGE_MIN_WIDTH,
  OG_IMAGE_MIN_HEIGHT,
  OG_IMAGE_SMALL_WIDTH,
  OG_IMAGE_SMALL_HEIGHT,
  OG_IMAGE_TARGET_RATIO,
  OG_IMAGE_RATIO_MIN,
  OG_IMAGE_RATIO_MAX,
  OG_IMAGE_HEAVY_BYTES,
  OG_IMAGE_MAX_BYTES,
} from "./thresholds";

export {
  OG_IMAGE_CHECK_ID,
  OG_IMAGE_UNREACHABLE_SUBTYPE,
  OG_IMAGE_UNVERIFIABLE_SUBTYPE,
  OG_IMAGE_SVG_SUBTYPE,
  OG_IMAGE_NOT_IMAGE_SUBTYPE,
  OG_IMAGE_UNDETERMINED_SUBTYPE,
  OG_IMAGE_TOO_SMALL_SUBTYPE,
  OG_IMAGE_SUBOPTIMAL_SUBTYPE,
  OG_IMAGE_TOO_LARGE_SUBTYPE,
  OG_IMAGE_HEAVY_SUBTYPE,
  subtypeFromImgFingerprint,
} from "./imageSubtypes";
